-- Crear BBDD
CREATE DATABASE pruebaTecnica;

-- USO BBDD
USE pruebaTecnica;

-- CREAR TABLA DOCUMENTOS
CREATE TABLE document (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_type VARCHAR(50) NOT NULL,
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    file_size BIGINT NOT NULL
);
 
-- CREAR TABLA DATA DE USUARIOS QUE CONTENDRÁ EL EXCEL
CREATE TABLE `user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255),
    `age` INT,
    `email` VARCHAR(255),
    PRIMARY KEY (`id`)
);
 
-- LISTAR TABLAS CREADAS
SHOW TABLES;
 
-- LISTAR DOCUMENTOS YA GUARDADOS
SELECT * FROM document;
 
-- LISTAS DATA DE USUARIOS ENVIADOS EN EL EXCEL
SELECT * FROM `user`